apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: metrics-server
spec:
  interval: 12h
  type: oci
  url: oci://registry-1.docker.io/bitnamicharts
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: metrics-server
spec:
  serviceAccountName: flux
  interval: 1h
  chart:
    spec:
      version: "7.4.0" # {"$imagepolicy": "flux-system:metrics-server:tag"}
      chart: metrics-server
      sourceRef:
        kind: HelmRepository
        name: metrics-server
      interval: 12h
  # https://artifacthub.io/packages/helm/bitnami/metrics-server
  values:
    extraArgs:
      - --kubelet-insecure-tls
